@startuml DiagCasUtilisation
title Cas d'utilisation
skinparam style strictuml
skinparam backgroundcolor #FFFFFE
'left to right direction
rectangle "SGA Système de Gestion de l'Apprentissage" {
    (CU01\nGérer\ncours) as gc #lightblue
    (CU02\nGérer\nquestions) as gq2 #lightblue
    (CU03\nGérer\ndevoirs) as gd #lightblue
    (CU04\nCorriger\ndevoir) as cd #lightblue
    (CU05\nGérer\nquestionnaires) as gq1 #lightblue
    (CU06\nCorriger\nquestionnaire) as cq #lightblue
    (CU07\nRemettre\ndevoir) as rd #lightgreen
    (CU08\nPasser\nquestionnaire) as pq #lightgreen
}
'actor "Administrateur" as A
actor "Enseignant" as P #lightblue
actor "Étudiant" as E #lightgreen
rectangle "<<actor>> **SGB** Système de Gestion des Bordereaux" as signets
P -- gc
P -- gq1
P -- gq2
P -- gd
P -- cd
P -- cq
'A -- ie
E -- pq
E -- rd
signets -u- gq1
signets -u- gd
signets -u- pq
signets -u- cd
signets -u- cq
@enduml

@startuml DependanceCasUtilisations
digraph foo {
    label="Dépendences (préalables) des cas d'utilisation"
    labelloc=t fontsize=24 fontname="Arial"
    node [style=filled; fillcolor=lightblue; fontname="Arial"; fontsize=12]
    CU01 [label="CU01 Gérer cours"]
    CU02 [label="CU02 Gérer questions"]
    CU03 [label="CU03 Gérer devoirs"]
    CU04 [label=<<B>*CU04 Corriger devoir</B>>]
    CU05 [label="CU05 Gérer questionnaires"]
    CU06 [label="CU06 Corriger questionnaire"]
    node [style=filled; fillcolor=lightgreen]
    CU07 [label="CU07 Remettre devoir"]
    CU08 [label=<<B>*CU08 Passer questionnaire</B>>]
    ' dependences
    CU04 -> CU07 -> CU03;
    CU03 -> CU01
    CU06 -> CU08 -> CU05;
    CU05 -> { CU01 CU02 }
    CU02 -> CU01
}
@enduml

